version: '3'

services:
  php-fpm:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    container_name: phpApp
    volumes:
      - ./app1:/var/www/html/app1
      #- ./app2:/var/www/html/app2#
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx-config:/etc/nginx/conf.d  # Mapeie o diretório de configurações
      - ./app1:/var/www/html/app1
      #- ./app2:/var/www/html/app2
    networks:
      - app-network
    depends_on:
      - php-fpm

  mysql:
    image: mysql
    container_name: mysql
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: escola
    volumes:
      - ./db/mysql:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=30M
    networks:
        - app-network

networks:
  app-network:
    driver: bridge
